### ISSUE TITLE
Bower.json ?

### ISSUE THREAD

**Issue by barillax** [cburgmer/inlineresources#10]
I know Bower has fallen out of fashion these days, but we have a project that still uses it for external libs. It would be convenient to have a build of `inlineresources` in the bower repo.

Failing that, I'd be amenable to creating and maintaining a shadow repo, a la https://github.com/nidheeshdas/bower-pdfkit that serves to simply point to the latest build. Let me know what you prefer!

**Comment by barillax** [comment]
Note: if you're against inlineresources being present in bower at all, I can also just maintain a repo like that but not publish it to bower, i.e.: simply reference it via a git URL for our project.

**Comment by cburgmer** [comment]
If it helps we can get a bower.json into the repo. Just out of interest, does bower not work with just a Github project URL?

**Comment by barillax** [comment]
It does, but I didn't see any committed build files in your repo, so I couldn't just point it at the inlineresources repo directly.

That is a good point, though - another option would be to start committing the dist folder so that old-school bower users could simply point at master.

**Comment by cburgmer** [comment]
I'd like to avoid committing build artefacts. Apart from being tedious (for every change you need to additionally add the dist folder to staging, especially cumbersome if using `git add -p` as a workflow) this just does not belong mixed together with the source.
I think I understand the position you are in though - the JS ecosystem's state of package and dependency management is annoying to say the least.
If you have an alternative option, I'd probably prefer that.

**Comment by barillax** [comment]
Yeah, I think the simplest approach is probably a bower.json in the repo. I don't know if you want to be responsible for publishing for builds into bower's repo or not, though, which is why I also open to the shadow repo approach. Whatever you prefer!

**Comment by cburgmer** [comment]
I understand now, so the bower.json goes hand in hand with a separate publishing step. Sorry, it's been a while since I've last had a look at bower.
Well, we could set up a hook with travisci and publish to bower on a new tag, but I assume I still need to take care of getting credentials. Also, the hook never really worked for me and that issue is probably still open today. So long for an easy solution :/
I certainly wouldn't mind if you pushed inlineresources into bower, would you?

**Comment by barillax** [comment]
Yeah, this blog post nicely summarizes some of the issues we're describing, I think: http://zpbappi.com/publishing-angular-autowrap-to-npm-bower-and-github-releases-from-travis-ci/

His solution in the end was to have separate repo just to hold the artifacts that are published into bower. He's managed to automate tagging and publishing everything via travis, which is pretty cool.

I think the most straightforward approach will be for me to create a separate repo, `inlineresources-bower`, that holds the bower.json and the artifacts we want to publish. Then, if you want to get fancy (or steal that guys scripts directly ;-) there's a path to automating all the things. I'll make sure you're a collaborator in that repo, of course.

Does that sound like a good plan?

**Comment by cburgmer** [comment]
Sounds good :)

**Comment by barillax** [comment]
Done, repo created here and registered with bower: https://github.com/barillax/inlineresources-bower

In the future, updating this bower component will entail:

- Cloning `inlineresources-bower`
- Running `npm install` within it
- Copying the contents of `node_modules/inlineresources/dist` into the root of the repo
- Changing the version `bower.json` to match the latest npm release
- Committing and pushing the changes
- Creating a new tag matching the semver of the npm release
