### ISSUE TITLE
Chrome bug getting baseURL of iframe

### ISSUE THREAD

**Issue by SamHasler** [cburgmer/inlineresources#6]
I think this line:

https://github.com/cburgmer/inlineresources/blob/6ce255d3fc9f04e6a6ace5a926d971b827908a6d/src/util.js#L8

Is failing with this bug:

https://code.google.com/p/chromium/issues/detail?id=484930

(I may only be seeing this issue because I am trying to use relative urls to CSS files that start with "`../../../`")

**Comment by cburgmer** [comment]
Any idea for a work around?

**Comment by SamHasler** [comment]
Didn't find one yesterday. Will look for one tomorrow as relative URLs would make using csscritic a lot easier. Ideally I'd like to have the tests in a different project (therefore different dir) than the CSS under test, and have

**Comment by SamHasler** [comment]
(Oops fatfingered close on my phone)

... and have csscritic vendorized in it's own project folder so my colleagues can use it on other projects without having to work around how our corporate proxy blocks npm install.

**Comment by cburgmer** [comment]
Technically inlineresources does not have any concept of iframes internally, so I would not consider this a limitation of inlineresources itself, but rather a limitation of its use alongside a setup with iframes. I don't intend to split hairs, rather I try to understand whether there's any workaround possibly on this level.

There is the option for inlineresources to receive an alternate baseUrl as parameter (see API), so there should be a work around for any consumer of the inlineresources API.

If this is rather an issue with csscritic, let's discuss there, and we'll might find an appropriate solution.

Does this make sense?

**Comment by SamHasler** [comment]
Yes, makes sense. Will try and test in Firefox for comparison (where
presumably baseurl works)

**Comment by SamHasler** [comment]
Actually, this doesn't seem to stop csscritic working properly. Ok to close?

**Comment by cburgmer** [comment]
Fine with me
