### ISSUE TITLE
Dispose of CSSOM as a dependency 

### ISSUE THREAD

**Issue by cburgmer** [cburgmer/inlineresources#7]
Use browser's own cssom once the fix for https://code.google.com/p/chromium/issues/detail?id=161644 has been rolled out in Chrome. This will fix the underlying issue for #5.

**Comment by cburgmer** [comment]
Blocked again by https://bugs.chromium.org/p/chromium/issues/detail?id=588129

**Comment by barillax** [comment]
I'm running into a related problem, where NV/CSSOM fails to parse a minified stylesheet. I'd settle for the broken font-face behavior of native CSSOM over this failure mode :(

I suspect I'll need to fork `inlineresources` to make a build without CSSOM included, unless there's a clever way to disable it at runtime to force it to use the browser's CSSOM. Thoughts?

**Comment by cburgmer** [comment]
Thanks for the feedback. It looks like a balancing act, either support font-face for Chrome or offer more reliability in general. Just not both.

With some activity with the newly reported bug for Chrome and the short release cycles, I'm positive that we can solve this issue here soonish.

In the meantime, there's no strict requirement on CSSOM (the JS implementation), if you don't provide it, the workaround is just not going to be triggered. I believe it depends on your packaging/build setup how difficult it is going to be to setup.

I'm on a bus right now, so excuse the brevity of the answer :)

**Comment by barillax** [comment]
No worries, I wouldn't expect you to disable CSSOM until the browser support was more stable. I'll play around to get a custom build for our project in the meantime.

**Comment by cburgmer** [comment]
Hey, after looking at the current code, I have to partially retract my initial statement. I believe building inlineresources without cssom will fail, as this is currently not handled at the import level. If you are willing to investigate, the following pointers might help:
- https://github.com/devongovett/browserify-optional
- npm --no-optional, see https://docs.npmjs.com/cli/install

**Comment by barillax** [comment]
Thanks for the tips! Will give it a go today.

**Comment by barillax** [comment]
Got it working. I'm not as familiar with the browserify way of doing things, so it's possible my approach isn't very idiomatic. Here's the changeset: https://github.com/barillax/inlineresources/commit/20a1135644ff143c80b8a263132c5a3501bf2e49

**Comment by cburgmer** [comment]
That looks good to me. I'm happy to take in the changes and release another version. Good with you?

**Comment by barillax** [comment]
OK, I'll create a PR momentarily!

**Comment by barillax** [comment]
Done: https://github.com/cburgmer/inlineresources/pull/9

**Comment by cburgmer** [comment]
There's yet another bug in Chrome (https://bugs.chromium.org/p/chromium/issues/detail?id=660663) and a work around committed in 6ab44b8b14f.

**Comment by kapouer** [comment]
This can be closed since version 0.4.0, right ?

**Comment by cburgmer** [comment]
This is still pending a release if I'm not mistaken.

**Comment by cburgmer** [comment]
Sorry for the noise. There was one failing test, which depended on the baseURI of the test runner. Took a while to figure out that the issue is indeed fixed in Chrome, just a corner case with an "illegal" relative URL was to blame.

**Comment by cburgmer** [comment]
Released
